### ISSUE TITLE
If missing `environment_variables.json` ci wants to onboard

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#996] opened 2018-06-15 17:48 UTC
I think this is a recent addition, but it breaks CI in that it won't startup due to:
```
[2018-06-15 10:44:38] DEBUG OnboardingService:  local configuration repo doesn't contain required configuration files
```
because in OnboardingService we have this:
`CONFIGURATION_FILES = ["users.json", "projects.json", "environment_variables.json"].freeze`
which is checked to make sure the repo is setup properly.
In this case, I think we should probably create defaults instead of going through onboarding.

**Comment by KrauseFx** [comment] 2018-06-15 17:55
```
def create_remote_configuration_files
      logger.debug("Creating remote configuration files `users.json` and `projects.json`")
      create_remote_json_file("users.json", json_string: serialized_users)
      create_remote_json_file("projects.json")
      create_remote_json_file("environment_variables.json")
    end
```

is created during onboarding. for now please create the file manually until we automate this

**Comment by KrauseFx** [comment] 2018-06-15 18:21
Looking at this, it does sound like it will cause some extra work to automatically migrate the user. New users will automatically have the file
 
The error message
```
local configuration repo doesn't contain required configuration files
```
is already very clear, I'll update it to explain how to easily create the file.

**Comment by KrauseFx** [comment] 2018-06-15 18:21
I'm gonna update it to call out the exact file name

**Comment by KrauseFx** [comment] 2018-06-15 18:31
It was my bad. Those files are generated on the fly anyway, no need to check if they exist. I'll update the PR, as well as added a comment mentioning this

**Comment by AndrewMcBurney** [comment] 2018-06-18 16:05
This was due to my oversight. I added `environment_variables.json` to the list , but the edge case described in #989  only exists when the `users.json` and `projects.json` files were not present in the `fastlane-ci-config` folder. I'll create a PR.

The problem is that if the `.keys` file exists with all the required variables set, but the `fastlane-ci-config` folder is empty (i.e., the git clone of the user's configuration repo was unsuccessful), it will not direct the user to onboarding, and the server will not be able to start due to an unrelated error.

**Comment by AndrewMcBurney** [comment] 2018-06-18 16:15
If you have all the required environment variables in `.keys`, have the `.fastlane/ci/fastlane-ci-config` folder locally, but don't have a `users.json` present in the folder, you will not be onboarded, and it will fail due to not being able to find the bot user account:

```
bundle exec rake dev DEBUG=1
bundle exec rackup --host 0.0.0.0 --port 8080 --env development
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[2018-06-18 12:13:14] INFO Services:  Reseting all services
[2018-06-18 12:13:14] INFO Launch:  development mode, aborting on any thread exceptions
[2018-06-18 12:13:14] INFO Services:  Reseting all services
[2018-06-18 12:13:15] DEBUG ConfigurationRepositoryService:  Checking that AndrewMcBurney/config/users.json is a json array
[2018-06-18 12:13:15] DEBUG ConfigurationRepositoryService:  Checking that AndrewMcBurney/config/projects.json is a json array
[2018-06-18 12:13:16] DEBUG Launch:  Starting workers to monitor projects
[2018-06-18 12:13:16] DEBUG JSONUserDataSource:  Using folder path for user data: /Users/andrewmcburney/.fastlane/ci/fastlane-ci-config
[2018-06-18 12:13:16] DEBUG UserService:  Attempting to login user with email mcburney.andrew13@gmail.com
[2018-06-18 12:13:16] DEBUG JSONUserDataSource:  Couldn't find user with email mcburney.andrew13@gmail.com in list of available accounts
bundler: failed to load command: rackup (/Users/andrewmcburney/.rbenv/versions/2.3.3/bin/rackup)
RuntimeError: Could not find ci_user for current setup, or the provided ci_user_password is incorrect.
```

**Comment by AndrewMcBurney** [comment] 2018-06-18 16:33
After a discussion with @taquitos, we've decided to close this issue. This problem should only affect alpha users who had an outdated version of the `fastlane-ci-config` repo. The solution to fixing this problem is to create the file `environment_variables.json` in the `~/.fastlane/ci/fastlane-ci-config` folder.

**Closed by AndrewMcBurney** 2018-06-18 16:33 UTC
Labels: regression, type: bug
